# Скачати розширення до VS Code, по посиланню нижче
# Name: REST Client
# VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

GET http://localhost:5500/getProductReview?productId=65cb593bf88b23255ef42f6a&take=1

###

GET http://localhost:5500/getProductReviewTotals?productId=65cb593bf88b23255ef42f6a
###

GET http://localhost:5500/getRevised
###

GET http://localhost:5500/authorize
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRkOWFkZmNjLTc4YTgtNGFmZS1iNTNmLThmNjMzOWEwY2FhMSIsImlhdCI6MTcwOTkxMTIwNX0.tidJKMBR0Ld0BrnchbhAy5s9A2u8JOiJq_cLziRF954

### Приклад POST запиту
POST http://localhost:5500/register HTTP/1.1
content-type: application/json

{   "name": "Joe",
    "surname": "Doe",
    "email": "sample@gmail.com",
    "password": "123"
}
### Приклад POST запиту
POST http://localhost:5500/login HTTP/1.1
content-type: application/json

{
    "email": "sample@gmail.com",
    "password": "123"
}

### Приклад POST запиту
# POST https://example.com/comments
# content-type: application/json
# {
#     "name": "sample",
#     "time": "Wed, 21 Oct 2015 18:27:50 GMT"
# }
